version: "3.7"
services:
  y-buyma-scraping-api:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ..:/app/:delegated
    container_name: y-buyma-scraping-api